# Snakemake workflow for various types of metagenomic analyses.

include: "rules/common.smk"
include: "rules/other.smk"

include: "rules/annotation.smk"
include: "rules/assembly.smk"
include: "rules/binning.smk"
include: "rules/classification.smk"
include: "rules/preprocessing.smk"
include: "rules/quantification.smk"

def all_input(wildcards):
    """
    Function defining all requested inputs for the rule all (below).
    """
    wanted_input = []

    if config["preprocess"] or config["fastqc"]:
        wanted_input.append(opj(config["report_path"], "samples_report.html"))

    if config["assembly"]:
        wanted_input.append(opj(config["report_path"], "assembly",
                                "assembly_stats.pdf"))
    return wanted_input

# master target rule
rule all:
    input: all_input
