name: nbis-meta

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # core packages for workflow
  - python>=3.9
  - snakemake-minimal>=7
  - mamba
  - pandas
  - seaborn
  - jupyter
  - biopython

  # packages required to create snakemake reports
  - pygments
  - jinja2
  - networkx
  - pygraphviz
  - imagemagick
