#default-resources: "slurm_account=<your-slurm-account>"
cluster-sidecar: "slurm-sidecar.py"
cluster-cancel: "scancel"
restart-times: "0"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"
local-cores: 1
latency-wait: "5"
use-conda: "True"
use-singularity: "False"
use-envmodules: "False"
jobs: "500"
printshellcmds: "True"
reason: "True"
rerun-triggers: "mtime"
keep-going: "True"
