cluster-sidecar: "cluster-sidecar.py"
cluster-cancel: "scancel"
restart-times: "0"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"
local-cores: 1
latency-wait: "5"
use-conda: "False"
use-singularity: "True"
use-envmodules: "True"
jobs: "500"
printshellcmds: "True"
reason: "True"
keep-going: "True"
rerun-triggers: "mtime"
